-- Your SQL goes here
CREATE TABLE `sources` (
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `weight` INTEGER NOT NULL DEFAULT 1,
    `url` TEXT NOT NULL,
    `added` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
