[package]
name = "mwr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
diesel = { version = "2.2.8", features = [
    "time",
    "returning_clauses_for_sqlite_3_35",
    "sqlite",
] }
rss = "2.0.12"
time = "0.3.39"
ureq = "3.0.8"
