[package]
name = "mwr"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.8", features = [
    "time",
    "returning_clauses_for_sqlite_3_35",
    "sqlite",
] }
time = "0.3.39"
