-- Your SQL goes here
CREATE TABLE pages (
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `source_id` INTEGER NOT NULL,
    `url` TEXT NOT NULL UNIQUE,
    `read` TIMESTAMP NULL,
    `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `added` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`source_id`) REFERENCES sources (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);
